### ISSUE TITLE
warning 提示，建议解决

### ISSUE THREAD

**Issue by yanbingbing** [uxcore/uxcore-input-form-field#1]
Warning: InputFormField: `key` is not a prop. Trying to access it will result in `undefined` being returned. If you need to access the same value within the child component, you should pass it as a different prop. (https://fb.me/react-special-props)

**Comment by eternalsky** [comment]
v15.x 版本开始报的 warning，目前组件整体还未向 v15.x 版本过渡，待统一过渡时统一解决。
